# Sprint 9 - Funciones, estructuras de datos y bucles en Python

Este notebook contiene la resolución de la Tasca S9.01.

El objetivo de este sprint es practicar los fundamentos de Python mediante la creación de funciones reutilizables, el uso de estructuras de datos, bucles, validaciones, procesamiento de archivos y automatización simple.

Cada ejercicio incluye:
- Una breve explicación del problema
- Una función reutilizable
- La ejecución de la función con su salida visible
- Una breve interpretación del resultado

In [72]:
import re
import numpy as np
import pandas as pd
from collections import Counter, defaultdict

# Nivel 1

En este nivel se resuelven cuatro problemas básicos utilizando funciones de Python, estructuras condicionales, diccionarios y procesamiento de texto.

## Ejercicio 1: Calculadora del Índice de Masa Corporal

El objetivo de este ejercicio es crear una función que calcule el Índice de Masa Corporal (IMC) a partir del peso y la altura de una persona.

La fórmula del IMC es:

IMC = peso / altura²

La función también valida los valores de entrada y clasifica el resultado del IMC en su categoría correspondiente.

In [73]:
def calculate_bmi(weight, height):
    """
    Calculate the Body Mass Index (BMI) and classify it into a category.

    Parameters:
    weight (float): Weight in kilograms.
    height (float): Height in meters.

    Returns:
    dict: BMI value and its category, or an error message for invalid inputs.
    """
    
    if not isinstance(weight, (int, float)) or not isinstance(height, (int, float)):
        return {
            "error": "Weight and height must be numeric values."
        }
    
    if weight <= 0 or height <= 0:
        return {
            "error": "Weight and height must be greater than zero."
        }
    
    if weight < 20 or weight > 300:
        return {
            "error": "Weight value is not reasonable."
        }
    
    if height < 0.5 or height > 2.5:
        return {
            "error": "Height value is not reasonable. Height must be provided in meters."
        }
    
    bmi = weight / (height ** 2)
    bmi = round(bmi, 2)
    
    if bmi < 18.5:
        category = "Underweight"
    elif bmi < 25:
        category = "Normal weight"
    elif bmi < 30:
        category = "Overweight"
    else:
        category = "Obesity"
    
    return {
        "bmi": bmi,
        "category": category
    }

In [74]:
calculate_bmi(98, 1.63)

{'bmi': 36.89, 'category': 'Obesity'}

In [75]:
calculate_bmi("seventy", 1.75)

{'error': 'Weight and height must be numeric values.'}

In [76]:
calculate_bmi(70, 0.2)

{'error': 'Height value is not reasonable. Height must be provided in meters.'}

### Ejecución interactiva

Además de probar la función con valores fijos, también se puede crear una versión interactiva que solicite el peso y la altura al usuario.

La función principal `calculate_bmi()` se mantiene separada de la entrada de datos para que el código sea más reutilizable, más fácil de probar y más claro.

In [77]:
def run_bmi_calculator():
    """
    Ask the user for weight and height, convert the inputs to float,
    and calculate the BMI using the calculate_bmi function.

    Returns:
    dict: BMI result or an error message if the input cannot be converted.
    """
    
    try:
        weight = float(input("Enter your weight in kilograms: "))
        height = float(input("Enter your height in meters: "))
    except ValueError:
        return {
            "error": "Weight and height must be numeric values."
        }
    
    return calculate_bmi(weight, height)

In [79]:
run_bmi_calculator()

{'bmi': 36.89, 'category': 'Obesity'}

### Interpretación

La función calcula el IMC utilizando el peso en kilogramos y la altura en metros.  
Antes de realizar el cálculo, valida que los valores introducidos sean numéricos, positivos y estén dentro de un rango razonable.

El resultado se devuelve como un diccionario en lugar de imprimirse, por lo que puede almacenarse y reutilizarse posteriormente.

Además, se ha añadido una versión interactiva que permite al usuario introducir el peso y la altura manualmente mediante `input()`. La lógica de entrada de datos se mantiene separada de la función principal para conservar un código más limpio y reutilizable.

El IMC es útil como indicador general, pero tiene limitaciones porque no diferencia entre masa grasa y masa muscular. Por este motivo, no debe interpretarse como un diagnóstico médico completo.

## Ejercicio 2: Convertidor de temperaturas

El objetivo de este ejercicio es crear una función que convierta una temperatura desde una unidad de origen a varias unidades de destino.

En este caso, la función acepta como unidades de entrada Celsius, Fahrenheit y Kelvin.  
A partir de la unidad introducida, primero convierte el valor a Celsius y después calcula el resto de conversiones.

El resultado se devuelve como un diccionario para que pueda almacenarse y reutilizarse posteriormente.

In [14]:
def convert_temperature(temperature, from_unit):
    """
    Convert a temperature value from Celsius, Fahrenheit or Kelvin
    into several temperature units.

    Parameters:
    temperature (float): Temperature value to convert.
    from_unit (str): Original temperature unit. Accepted values: 'C', 'F', 'K'.

    Returns:
    dict: Converted temperature values or an error message for invalid inputs.
    """
    
    if not isinstance(temperature, (int, float)):
        return {
            "error": "Temperature must be a numeric value."
        }
    
    if not isinstance(from_unit, str):
        return {
            "error": "Temperature unit must be a string."
        }
    
    from_unit = from_unit.upper()
    
    if from_unit not in ["C", "F", "K"]:
        return {
            "error": "Invalid unit. Use 'C' for Celsius, 'F' for Fahrenheit or 'K' for Kelvin."
        }
    
    if from_unit == "C":
        celsius = temperature
    elif from_unit == "F":
        celsius = (temperature - 32) * 5 / 9
    else:
        celsius = temperature - 273.15
    
    if celsius < -273.15:
        return {
            "error": "Temperature cannot be below absolute zero."
        }
    
    conversions = {
        "Celsius": round(celsius, 2),
        "Fahrenheit": round((celsius * 9 / 5) + 32, 2),
        "Kelvin": round(celsius + 273.15, 2),
        "Rankine": round((celsius + 273.15) * 9 / 5, 2),
        "Reaumur": round(celsius * 4 / 5, 2)
    }
    
    return conversions

In [15]:
convert_temperature(25, "C")

{'Celsius': 25,
 'Fahrenheit': 77.0,
 'Kelvin': 298.15,
 'Rankine': 536.67,
 'Reaumur': 20.0}

In [16]:
convert_temperature(77, "F")

{'Celsius': 25.0,
 'Fahrenheit': 77.0,
 'Kelvin': 298.15,
 'Rankine': 536.67,
 'Reaumur': 20.0}

In [17]:
convert_temperature(298.15, "k")

{'Celsius': 25.0,
 'Fahrenheit': 77.0,
 'Kelvin': 298.15,
 'Rankine': 536.67,
 'Reaumur': 20.0}

In [18]:
convert_temperature("hot", "C")

{'error': 'Temperature must be a numeric value.'}

In [19]:
convert_temperature(-300, "C")

{'error': 'Temperature cannot be below absolute zero.'}

### Ejecución interactiva

Además de probar la función con valores fijos, también se puede crear una versión interactiva que solicite al usuario la temperatura y la unidad de origen.

La función principal `convert_temperature()` se mantiene separada de la entrada de datos para conservar un código más reutilizable y fácil de probar.

In [20]:
def run_temperature_converter():
    """
    Ask the user for a temperature value and its unit,
    then convert it using the convert_temperature function.

    Returns:
    dict: Converted temperature values or an error message.
    """
    
    try:
        temperature = float(input("Enter the temperature value: "))
        from_unit = input("Enter the original unit (C, F or K): ")
    except ValueError:
        return {
            "error": "Temperature must be a numeric value."
        }
    
    return convert_temperature(temperature, from_unit)

In [21]:
run_temperature_converter()

{'Celsius': 25.0,
 'Fahrenheit': 77.0,
 'Kelvin': 298.15,
 'Rankine': 536.67,
 'Reaumur': 20.0}

### Interpretación

La función convierte una temperatura desde Celsius, Fahrenheit o Kelvin a varias unidades de temperatura.  
Antes de realizar los cálculos, valida que el valor de temperatura sea numérico y que la unidad introducida sea válida.

Para evitar escribir muchas condiciones repetidas, la función utiliza Celsius como unidad intermedia. Primero convierte la temperatura introducida a Celsius y después calcula el resto de unidades.

El resultado se devuelve como un diccionario, por lo que puede almacenarse y reutilizarse posteriormente. También se ha añadido una versión interactiva con `input()` para permitir que el usuario introduzca los datos manualmente.

## Ejercicio 3: Contador de palabras de un texto

El objetivo de este ejercicio es crear una función que reciba un texto y cuente cuántas veces aparece cada palabra.

Antes de contar las palabras, el texto se transforma a minúsculas y se eliminan los signos de puntuación para evitar que palabras como `Hola`, `hola,` y `hola` se cuenten como palabras diferentes.

Como funcionalidad extra, también se calcula la longitud media de las palabras del texto.

In [22]:
def count_words(text):
    """
    Count the frequency of each word in a text and calculate the average word length.

    Parameters:
    text (str): Input text.

    Returns:
    dict: Word frequencies and average word length, or an error message for invalid inputs.
    """
    
    if not isinstance(text, str):
        return {
            "error": "Input must be a text string."
        }
    
    if text.strip() == "":
        return {
            "error": "Input text cannot be empty."
        }
    
    text = text.lower()
    cleaned_text = re.sub(r"[^\w\sáéíóúàèìòùäëïöüñç]", "", text)
    words = cleaned_text.split()
    
    if len(words) == 0:
        return {
            "error": "No valid words found in the text."
        }
    
    word_frequencies = dict(Counter(words))
    average_word_length = sum(len(word) for word in words) / len(words)
    
    return {
        "word_frequencies": word_frequencies,
        "average_word_length": round(average_word_length, 2)
    }

In [23]:
count_words("Hola com va? Hola, molt bé!")

{'word_frequencies': {'hola': 2, 'com': 1, 'va': 1, 'molt': 1, 'bé': 1},
 'average_word_length': 3.17}

In [24]:
count_words("Hola com va?")

{'word_frequencies': {'hola': 1, 'com': 1, 'va': 1},
 'average_word_length': 3.0}

In [25]:
count_words(12345)

{'error': 'Input must be a text string.'}

In [26]:
count_words("     ")

{'error': 'Input text cannot be empty.'}

In [27]:
count_words("!!! ??? ...")

{'error': 'No valid words found in the text.'}

### Ejecución interactiva

Además de probar la función con textos fijos, también se puede crear una versión interactiva que solicite un texto al usuario.

La función principal `count_words()` se mantiene separada de la entrada de datos para que el código sea más reutilizable, más claro y más fácil de probar.

In [29]:
def run_word_counter():
    """
    Ask the user for a text and count the frequency of each word
    using the count_words function.

    Returns:
    dict: Word frequencies and average word length, or an error message.
    """
    
    text = input("Enter a text: ")
    
    return count_words(text)

In [30]:
run_word_counter()

{'word_frequencies': {'hola': 2, 'com': 1, 'va': 1, 'molt': 1, 'bé': 1},
 'average_word_length': 3.17}

### Interpretación

La función recibe un texto, valida que la entrada sea una cadena de texto y comprueba que no esté vacía.  
Después convierte el texto a minúsculas y elimina los signos de puntuación para que el conteo de palabras sea más consistente.

A continuación, el texto limpio se divide en palabras y se calcula la frecuencia de cada una mediante `Counter`.  
Además, se calcula la longitud media de las palabras como funcionalidad extra.

El resultado se devuelve como un diccionario, por lo que puede almacenarse y reutilizarse posteriormente.

También se ha añadido una versión interactiva con `input()` para que el usuario pueda introducir manualmente el texto que desea analizar, manteniendo separada la lógica de entrada de datos de la función principal.

## Ejercicio 4: Diccionario inverso con posibilidad de duplicados

El objetivo de este ejercicio es crear una función que invierta un diccionario, intercambiando sus claves y valores.

Si todos los valores del diccionario original son únicos, la inversión es directa.  
Sin embargo, si existen valores duplicados, la función debe evitar la pérdida de información agrupando las claves originales asociadas a ese valor en una lista.

Además, la función devuelve un mensaje de advertencia cuando detecta valores duplicados.

In [31]:
def reverse_dictionary(input_dict):
    """
    Reverse the keys and values of a dictionary.
    If duplicated values are found, all related keys are stored in a list.

    Parameters:
    input_dict (dict): Dictionary to reverse.

    Returns:
    dict: Reversed dictionary and warning information if duplicated values exist.
    """
    
    if not isinstance(input_dict, dict):
        return {
            "error": "Input must be a dictionary."
        }
    
    if len(input_dict) == 0:
        return {
            "error": "Input dictionary cannot be empty."
        }
    
    reversed_dict = {}
    duplicated_values = {}
    
    for key, value in input_dict.items():
        if value in reversed_dict:
            if not isinstance(reversed_dict[value], list):
                reversed_dict[value] = [reversed_dict[value]]
            
            reversed_dict[value].append(key)
            duplicated_values[value] = reversed_dict[value]
        else:
            reversed_dict[value] = key
    
    if duplicated_values:
        return {
            "warning": "Duplicated values were found. Related keys have been grouped in lists.",
            "duplicated_values": duplicated_values,
            "reversed_dictionary": reversed_dict
        }
    
    return {
        "reversed_dictionary": reversed_dict
    }

In [32]:
sample_dict_1 = {
    "a": 1,
    "b": 2,
    "c": 3
}

reverse_dictionary(sample_dict_1)

{'reversed_dictionary': {1: 'a', 2: 'b', 3: 'c'}}

In [33]:
sample_dict_2 = {
    "a": "apple",
    "b": "banana",
    "c": "banana",
    "d": "orange"
}

reverse_dictionary(sample_dict_2)

{'warning': 'Duplicated values were found. Related keys have been grouped in lists.',
 'duplicated_values': {'banana': ['b', 'c']},
 'reversed_dictionary': {'apple': 'a', 'banana': ['b', 'c'], 'orange': 'd'}}

In [34]:
sample_dict_3 = {
    "user_1": "yes",
    "user_2": "no",
    "user_3": "yes",
    "user_4": "maybe",
    "user_5": "no"
}

reverse_dictionary(sample_dict_3)

{'warning': 'Duplicated values were found. Related keys have been grouped in lists.',
 'duplicated_values': {'yes': ['user_1', 'user_3'],
  'no': ['user_2', 'user_5']},
 'reversed_dictionary': {'yes': ['user_1', 'user_3'],
  'no': ['user_2', 'user_5'],
  'maybe': 'user_4'}}

In [35]:
reverse_dictionary(["a", "b", "c"])

{'error': 'Input must be a dictionary.'}

### Ejecución interactiva

Además de probar la función con diccionarios predefinidos, también se puede crear una versión interactiva que permita al usuario construir un diccionario manualmente.

En lugar de pedir al usuario que escriba todo el diccionario en una sola línea, la función solicita pares de clave y valor uno por uno.  
Cuando el usuario escribe `stop`, la entrada de datos termina y se llama a la función principal `reverse_dictionary()`.

De esta forma, no es necesario utilizar librerías adicionales y la función principal se mantiene separada de la entrada de datos.

In [36]:
def run_reverse_dictionary():
    """
    Build a dictionary interactively by asking the user for key-value pairs,
    then reverse it using the reverse_dictionary function.

    Returns:
    dict: Reversed dictionary, warning information, or an error message.
    """
    
    user_dict = {}
    
    while True:
        key = input("Enter a key or type 'stop' to finish: ")
        
        if key.lower() == "stop":
            break
        
        value = input("Enter the value for this key: ")
        user_dict[key] = value
    
    return reverse_dictionary(user_dict)

In [37]:
run_reverse_dictionary()

{'warning': 'Duplicated values were found. Related keys have been grouped in lists.',
 'duplicated_values': {'Python': ['student_1', 'student_3']},
 'reversed_dictionary': {'Python': ['student_1', 'student_3'],
  'SQL': 'student_2'}}

### Interpretación

La función invierte las claves y los valores de un diccionario.  
Cuando los valores del diccionario original son únicos, la inversión se realiza de forma directa.

Si se detectan valores duplicados, la función evita la pérdida de información agrupando todas las claves originales asociadas a ese valor dentro de una lista.  
Además, devuelve una advertencia y un diccionario adicional con los valores duplicados detectados.

El resultado se devuelve como un diccionario estructurado, por lo que puede almacenarse y reutilizarse posteriormente.

También se ha añadido una versión interactiva que permite construir un diccionario manualmente mediante pares de clave y valor.  
Esta versión utiliza únicamente `input()`, un bucle `while` y un diccionario vacío que se va completando con los datos introducidos por el usuario, sin necesidad de utilizar librerías adicionales.

# Nivel 2

En este nivel se resuelven ejercicios que requieren trabajar con archivos externos, estructuras de datos anidadas y conversión de tipos de datos.

## Ejercicio 1: Contador y organizador de palabras desde un archivo TXT

El objetivo de este ejercicio es leer un archivo `.txt`, contar la frecuencia de cada palabra y organizar el resultado según la letra inicial de cada palabra.

La salida será un diccionario anidado.  
La primera clave representa la letra inicial y, dentro de cada letra, se almacenan las palabras ordenadas alfabéticamente junto con su frecuencia.

Por ejemplo, la estructura esperada es:

{
    "a": {
        "agua": 1,
        "alba": 4
    },
    "b": {
        "baco": 1,
        "blanca": 3
    }
}

El archivo `.txt` se encuentra en la misma carpeta que el notebook, por lo que se utiliza una ruta relativa. Esto permite que el proyecto sea más reproducible al subirlo a GitHub.

In [38]:
def count_and_sort_words_from_file(file_path):
    """
    Read a TXT file, count word frequencies and organize words by their first letter.

    Parameters:
    file_path (str): Path to the TXT file.

    Returns:
    dict: A nested dictionary where each key is a first letter and each value is
          another dictionary with words and their frequencies.
    """
    
    if not isinstance(file_path, str):
        return {
            "error": "File path must be a string."
        }
    
    try:
        with open(file_path, "r", encoding="utf-8") as file:
            text = file.read()
    except FileNotFoundError:
        return {
            "error": "File not found. Please check the file path."
        }
    except Exception as error:
        return {
            "error": f"An unexpected error occurred: {error}"
        }
    
    if text.strip() == "":
        return {
            "error": "The file is empty."
        }
    
    text = text.lower()
    cleaned_text = re.sub(r"[^\w\sáéíóúàèìòùäëïöüñç]", "", text)
    words = cleaned_text.split()
    
    if len(words) == 0:
        return {
            "error": "No valid words found in the file."
        }
    
    word_frequencies = Counter(words)
    organized_words = defaultdict(dict)
    
    for word in sorted(word_frequencies):
        first_letter = word[0]
        organized_words[first_letter][word] = word_frequencies[word]
    
    return dict(sorted(organized_words.items()))

In [41]:
poem_word_count = count_and_sort_words_from_file("tu me quieres blanca.txt")
type(poem_word_count), len(poem_word_count)

(dict, 20)

In [42]:
{letter: poem_word_count[letter] for letter in list(poem_word_count.keys())[:3]}

{'a': {'a': 3,
  'agua': 1,
  'al': 2,
  'alba': 4,
  'alcobas': 1,
  'alimenta': 1,
  'alma': 1,
  'amarga': 1,
  'azucena': 1},
 'b': {'baco': 1,
  'banquete': 1,
  'bebe': 1,
  'blanca': 3,
  'boca': 1,
  'bosques': 1,
  'buen': 1},
 'c': {'cabañas': 1,
  'carnes': 2,
  'casta': 3,
  'cerrada': 1,
  'con': 4,
  'conservas': 1,
  'copas': 1,
  'corola': 1,
  'corriste': 1,
  'cuando': 2,
  'cubierto': 1,
  'cuerpo': 1,
  'cuáles': 1}}

### Visualización del resultado en formato tabla

Aunque la función devuelve un diccionario anidado, para visualizar mejor el resultado en el notebook se convierte una parte del diccionario en un `DataFrame`.

In [43]:
word_count_rows = []

for letter, words in poem_word_count.items():
    for word, frequency in words.items():
        word_count_rows.append({
            "initial_letter": letter,
            "word": word,
            "frequency": frequency
        })

poem_word_count_df = pd.DataFrame(word_count_rows)
poem_word_count_df.head(15)

   initial_letter      word  frequency
0               a         a          3
1               a      agua          1
2               a        al          2
3               a      alba          4
4               a   alcobas          1
5               a  alimenta          1
6               a      alma          1
7               a    amarga          1
8               a   azucena          1
9               b      baco          1
10              b  banquete          1
11              b      bebe          1
12              b    blanca          3
13              b      boca          1
14              b   bosques          1

In [46]:
poem_word_count["a"]

{'a': 3,
 'agua': 1,
 'al': 2,
 'alba': 4,
 'alcobas': 1,
 'alimenta': 1,
 'alma': 1,
 'amarga': 1,
 'azucena': 1}

In [45]:
poem_word_count_df[poem_word_count_df["initial_letter"] == "a"]

  initial_letter      word  frequency
0              a         a          3
1              a      agua          1
2              a        al          2
3              a      alba          4
4              a   alcobas          1
5              a  alimenta          1
6              a      alma          1
7              a    amarga          1
8              a   azucena          1

In [47]:
poem_word_count_df.sort_values(
    by="frequency",
    ascending=False
).head(10)

    initial_letter     word  frequency
69               m       me         10
111              t       tú          8
29               d       de          8
60               l      las          7
91               q  quieres          6
89               q      que          6
117              y        y          5
62               l      los          4
35               e       el          4
37               e       en          4

### Interpretación

La función lee el archivo `tu me quieres blanca.txt` utilizando una ruta relativa, ya que el archivo se encuentra en la misma carpeta que el notebook. Esto hace que el proyecto sea más reproducible al subirlo a GitHub.

Después de leer el archivo, el texto se convierte a minúsculas y se eliminan los signos de puntuación para evitar que una misma palabra se cuente de forma diferente por aparecer con mayúsculas, comas, puntos u otros signos.

A continuación, el texto limpio se divide en palabras y se calcula la frecuencia de cada una mediante `Counter`.  
El resultado principal se devuelve como un diccionario anidado, donde la primera clave corresponde a la letra inicial de cada palabra y el segundo nivel contiene las palabras ordenadas alfabéticamente junto con su frecuencia.

Para mejorar la visualización en el notebook, el diccionario anidado también se transforma en un `DataFrame`. Esto permite consultar las palabras y sus frecuencias de una forma más clara, ordenada y adecuada para un análisis de datos.

Finalmente, se realizan pruebas adicionales para mostrar algunos grupos de letras y para comprobar que la función gestiona correctamente el caso en que el archivo no existe.

## Ejercicio 2: Conversión de tipos de datos

El objetivo de este ejercicio es crear una función que reciba una lista con diferentes tipos de datos y los separe en dos grupos:

- Valores que se pueden convertir a `float`
- Valores que no se pueden convertir a `float`

La lista puede contener elementos simples, listas internas o tuplas internas.  
Por este motivo, primero se aplana la estructura para poder analizar todos los valores individualmente.

In [94]:
def flatten(items):
    """
    Recursively flatten lists and tuples.

    Parameters:
    items (list or tuple): A nested structure containing values, lists or tuples.

    Returns:
    list: A flat list with all individual elements.
    """
    
    flattened_items = []
    
    for item in items:
        if isinstance(item, (list, tuple)):
            flattened_items.extend(flatten(item))
        else:
            flattened_items.append(item)
    
    return flattened_items


def convert_values_to_float(data):
    """
    Convert all possible values from a nested data structure into floats.

    Parameters:
    data (list): A list that may contain values, lists or tuples.

    Returns:
    tuple: A tuple with two lists:
           - values converted to float
           - values that could not be converted
    """
    
    if not isinstance(data, list):
        return {
            "error": "Input must be a list."
        }
    
    converted_values = []
    not_converted_values = []
    
    flat_data = flatten(data)
    
    for item in flat_data:
        try:
            converted_values.append(float(item))
        except (ValueError, TypeError):
            not_converted_values.append(item)
    
    return converted_values, not_converted_values

In [95]:
sample_data = [
    '1.3',
    'one',
    '1e10',
    'seven',
    '3-1/2',
    ('2', 1, 1.4, 'not-a-number'),
    [1, 2, '3', '3.4']
]

convert_values_to_float(sample_data)

([1.3, 10000000000.0, 2.0, 1.0, 1.4, 1.0, 2.0, 3.0, 3.4],
 ['one', 'seven', '3-1/2', 'not-a-number'])

In [96]:
convert_values_to_float(sample_data)

([1.3, 10000000000.0, 2.0, 1.0, 1.4, 1.0, 2.0, 3.0, 3.4],
 ['one', 'seven', '3-1/2', 'not-a-number'])

In [97]:
converted, not_converted = convert_values_to_float(sample_data)

In [98]:
converted

[1.3, 10000000000.0, 2.0, 1.0, 1.4, 1.0, 2.0, 3.0, 3.4]

In [99]:
not_converted

['one', 'seven', '3-1/2', 'not-a-number']

In [100]:
convert_values_to_float("not a list")

{'error': 'Input must be a list.'}

### Interpretación

La función recibe una lista que puede contener diferentes tipos de datos, incluyendo listas y tuplas internas.  
Primero valida que la entrada principal sea una lista y después aplana la estructura para poder analizar todos los elementos de forma individual.

La función auxiliar `flatten()` se define por separado para mantener el código más claro y reutilizable.

Para cada elemento, la función intenta convertirlo a `float` mediante un bloque `try/except`.  
Los valores que se pueden convertir se guardan en una lista como números flotantes, mientras que los valores que no se pueden convertir se guardan en otra lista.

El resultado se devuelve como una tupla con dos listas: la primera contiene los valores convertidos a `float` y la segunda contiene los valores no convertibles.

También se comprueba un caso de entrada no válida para mostrar que la función gestiona correctamente los errores.

# Nivel 3

En este nivel se resuelven ejercicios más avanzados que combinan validación, generación aleatoria, procesamiento de archivos y análisis de datos.

## Ejercicio 1: Generador de contraseñas

El objetivo de este ejercicio es crear una función que genere contraseñas aleatorias y más seguras.

La función permite configurar diferentes criterios:

- Longitud de la contraseña
- Inclusión de letras mayúsculas
- Inclusión de letras minúsculas
- Inclusión de números
- Inclusión de signos o caracteres especiales

La función debe asegurar que todos los criterios seleccionados se cumplan al menos una vez en la contraseña generada.

In [56]:
def crear_contrasenya(longitud, majuscules=True, minuscules=True, numeros=True, signes=False):
    """
    Generate a random password based on selected character groups.

    Parameters:
    longitud (int): Password length.
    majuscules (bool): Include uppercase letters.
    minuscules (bool): Include lowercase letters.
    numeros (bool): Include numbers.
    signes (bool): Include special characters.

    Returns:
    str or dict: Generated password, or an error message for invalid inputs.
    """
    
    if not isinstance(longitud, int):
        return {
            "error": "Password length must be an integer."
        }
    
    if longitud <= 0:
        return {
            "error": "Password length must be greater than zero."
        }
    
    if not all(isinstance(option, bool) for option in [majuscules, minuscules, numeros, signes]):
        return {
            "error": "Character group options must be boolean values."
        }
    
    character_groups = {}
    
    if majuscules:
        character_groups["uppercase"] = list("ABCDEFGHIJKLMNOPQRSTUVWXYZ")
    
    if minuscules:
        character_groups["lowercase"] = list("abcdefghijklmnopqrstuvwxyz")
    
    if numeros:
        character_groups["numbers"] = list("0123456789")
    
    if signes:
        character_groups["symbols"] = list(",-$?¿!@#%&*")
    
    if len(character_groups) == 0:
        return {
            "error": "At least one character group must be selected."
        }
    
    if longitud < len(character_groups):
        return {
            "error": "Password length is too short for the selected criteria."
        }
    
    password_characters = []
    
    for group in character_groups.values():
        password_characters.append(np.random.choice(group))
    
    all_characters = []
    
    for group in character_groups.values():
        all_characters.extend(group)
    
    remaining_length = longitud - len(password_characters)
    
    if remaining_length > 0:
        password_characters.extend(
            np.random.choice(all_characters, size=remaining_length)
        )
    
    np.random.shuffle(password_characters)
    
    password = "".join(password_characters)
    
    return password

In [57]:
crear_contrasenya(10, True, True, True, True)

'7d?IW#tlZQ'

In [60]:
crear_contrasenya(2, True, True, True, True)

{'error': 'Password length is too short for the selected criteria.'}

In [61]:
crear_contrasenya(10, False, False, False, False)

{'error': 'At least one character group must be selected.'}

### Comprobación de los criterios de la contraseña

Para comprobar que la contraseña generada cumple los criterios seleccionados, se define una función auxiliar que verifica si contiene mayúsculas, minúsculas, números y signos.

In [62]:
def check_password_criteria(password):
    """
    Check which character groups are present in a password.

    Parameters:
    password (str): Password to check.

    Returns:
    dict: Boolean values indicating whether each character group is present.
    """
    
    return {
        "has_uppercase": any(char.isupper() for char in password),
        "has_lowercase": any(char.islower() for char in password),
        "has_number": any(char.isdigit() for char in password),
        "has_symbol": any(char in ",-$?¿!@#%&*" for char in password)
    }

In [63]:
password = crear_contrasenya(10, True, True, True, True)

password, check_password_criteria(password)

('IJqr0qcNr¿',
 {'has_uppercase': True,
  'has_lowercase': True,
  'has_number': True,
  'has_symbol': True})

### Interpretación

La función genera una contraseña aleatoria utilizando `np.random.choice()` y `np.random.shuffle()` del módulo random de NumPy.

Antes de generar la contraseña, se validan los parámetros de entrada: la longitud debe ser un número entero positivo y las opciones de los grupos de caracteres deben ser valores booleanos.

Para asegurar que todos los criterios seleccionados se cumplan, la función primero selecciona un carácter de cada grupo activo. Después, completa el resto de la longitud de la contraseña utilizando todos los caracteres disponibles.

Finalmente, los caracteres se mezclan para evitar una estructura predecible y se unen en una cadena de texto mediante `"".join()`.

El resultado se devuelve como una cadena de texto, por lo que puede almacenarse y reutilizarse posteriormente. También se añade una función auxiliar para comprobar que la contraseña generada cumple los criterios seleccionados.

## Ejercicio 2: Procesamiento simple de datos de fútbol

El objetivo de este ejercicio es procesar un archivo `.txt` que contiene resultados históricos de partidos de fútbol catalán.

A partir de este archivo, se deben obtener los siguientes resultados:

- El número total de goles marcados por cada equipo
- El equipo más goleador
- El equipo que más goles ha recibido
- La clasificación global, asignando:
  - 3 puntos por victoria
  - 1 punto por empate
  - 0 puntos por derrota

El archivo `historic partits.txt` se encuentra en la misma carpeta que el notebook, por lo que se utiliza una ruta relativa.

In [64]:
def process_football_results(file_path):
    """
    Process a TXT file with football match results and calculate team statistics.

    Parameters:
    file_path (str): Path to the TXT file.

    Returns:
    dict: A dictionary containing:
          - total goals by team
          - highest scoring team
          - team with most goals conceded
          - global classification as a pandas DataFrame
    """
    
    if not isinstance(file_path, str):
        return {
            "error": "File path must be a string."
        }
    
    try:
        with open(file_path, "r", encoding="utf-8") as file:
            lines = file.readlines()
    except FileNotFoundError:
        return {
            "error": "File not found. Please check the file path."
        }
    except Exception as error:
        return {
            "error": f"An unexpected error occurred: {error}"
        }
    
    if len(lines) == 0:
        return {
            "error": "The file is empty."
        }
    
    team_stats = defaultdict(lambda: {
        "played": 0,
        "wins": 0,
        "draws": 0,
        "losses": 0,
        "goals_for": 0,
        "goals_against": 0,
        "points": 0
    })
    
    for line in lines:
        line = line.strip()
        
        if line == "":
            continue
        
        parts = line.split("\t")
        
        if len(parts) != 3:
            return {
                "error": f"Invalid line format: {line}"
            }
        
        home_team = parts[0]
        score = parts[1]
        away_team = parts[2]
        
        try:
            home_goals, away_goals = score.split("-")
            home_goals = int(home_goals)
            away_goals = int(away_goals)
        except ValueError:
            return {
                "error": f"Invalid score format: {score}"
            }
        
        team_stats[home_team]["played"] += 1
        team_stats[away_team]["played"] += 1
        
        team_stats[home_team]["goals_for"] += home_goals
        team_stats[home_team]["goals_against"] += away_goals
        
        team_stats[away_team]["goals_for"] += away_goals
        team_stats[away_team]["goals_against"] += home_goals
        
        if home_goals > away_goals:
            team_stats[home_team]["wins"] += 1
            team_stats[away_team]["losses"] += 1
            team_stats[home_team]["points"] += 3
            
        elif home_goals < away_goals:
            team_stats[away_team]["wins"] += 1
            team_stats[home_team]["losses"] += 1
            team_stats[away_team]["points"] += 3
            
        else:
            team_stats[home_team]["draws"] += 1
            team_stats[away_team]["draws"] += 1
            team_stats[home_team]["points"] += 1
            team_stats[away_team]["points"] += 1
    
    classification = pd.DataFrame.from_dict(team_stats, orient="index")
    classification = classification.reset_index().rename(columns={"index": "team"})
    
    classification = classification.sort_values(
        by=["points", "goals_for"],
        ascending=[False, False]
    ).reset_index(drop=True)
    
    total_goals_by_team = dict(
        zip(classification["team"], classification["goals_for"])
    )
    
    highest_scoring_team = classification.loc[
        classification["goals_for"].idxmax(),
        "team"
    ]
    
    most_conceded_team = classification.loc[
        classification["goals_against"].idxmax(),
        "team"
    ]
    
    return {
        "total_goals_by_team": total_goals_by_team,
        "highest_scoring_team": highest_scoring_team,
        "most_conceded_team": most_conceded_team,
        "classification": classification
    }

In [65]:
football_results = process_football_results("historic partits.txt")
type(football_results)

dict

In [66]:
football_results["highest_scoring_team"]

'Figueres'

In [70]:
football_results["most_conceded_team"]

'Vilafranca'

In [71]:
football_results["classification"][["team", "goals_for"]]

                   team  goals_for
0             Girona FC        139
1            Llagostera        159
2              Sabadell        141
3              Cornellà        147
4          RCD Espanyol        131
5              Figueres        161
6       Lleida Esportiu        129
7              Terrassa        147
8          FC Barcelona        125
9            Vilafranca        157
10             Badalona        134
11  Nàstic de Tarragona        130
12        Reus Deportiu        119
13           Granollers        122
14                 Olot        132
15          Sant Andreu        123
16              Manlleu        106
17           Cerdanyola        117
18                 Prat        106
19               Europa         93

In [68]:
football_results["classification"].head(10)

,team,played,wins,draws,losses,goals_for,goals_against,points
0,Girona FC,47,31,3,13,139,94,96
1,Llagostera,56,29,7,20,159,142,94
2,Sabadell,48,26,7,15,141,121,85
3,Cornellà,54,25,7,22,147,146,82
4,RCD Espanyol,55,23,11,21,131,144,80
5,Figueres,56,23,10,23,161,154,79
6,Lleida Esportiu,52,23,6,23,129,133,75
7,Terrassa,57,20,14,23,147,164,74
8,FC Barcelona,44,22,7,15,125,115,73
9,Vilafranca,57,20,12,25,157,172,72

In [69]:
process_football_results("wrong_file.txt")

{'error': 'File not found. Please check the file path.'}

### Interpretación

La función lee el archivo `historic partits.txt` utilizando una ruta relativa, ya que el archivo se encuentra en la misma carpeta que el notebook.

Cada línea del archivo representa un partido y contiene el equipo local, el resultado y el equipo visitante.  
La función separa cada línea, extrae los goles de cada equipo y actualiza las estadísticas correspondientes.

Para cada equipo se calculan los partidos jugados, victorias, empates, derrotas, goles a favor, goles en contra y puntos.  
La puntuación se asigna siguiendo el criterio del ejercicio: 3 puntos por victoria, 1 punto por empate y 0 puntos por derrota.

El resultado principal de la clasificación se transforma en un `DataFrame` de pandas para facilitar su lectura y análisis.  
La tabla se ordena por puntos de mayor a menor y, en caso de igualdad, por goles a favor.

Además, la función devuelve el total de goles marcados por cada equipo, el equipo más goleador y el equipo que más goles ha recibido.